#include "src/main.c"

#include "src/convert_anim.c"
#include "src/convert_collada.c"
#include "src/convert_geometry.c"
#include "src/convert_image.c"
#include "src/convert_material.c"
#include "src/convert_node.c"
#include "src/convert_skin.c"
#include "src/objmap.c"
#include "src/tga.c"

#include "../libdae/src/dae.c"
#include "../libdae/src/daeu.c"

#include "../taascene/src/scene.c"
#include "../taascene/src/sceneanim.c"
#include "../taascene/src/scenefile.c"
#include "../taascene/src/scenematerial.c"
#include "../taascene/src/scenemesh.c"
#include "../taascene/src/scenenode.c"
#include "../taascene/src/sceneskel.c"
#include "../taascene/src/scenetexture.c"

#include "../taasdk/src/filestream.c"
#include "../taasdk/src/log.c"
#include "../taasdk/src/path.c"
#include "../taasdk/src/system.c"
#include "../taasdk/src/uri.c"
